language: csharp
dist: trusty
mono: none
dotnet: 2.0.0
solution: NameSorter/NameSorter.sln
install:
- dotnet restore
script:
- dotnet build
- dotnet test NameSorter/NameSorter.UnitTest/NameSorter.UnitTest.csproj